services:
  db:
    image: postgres:15-trixie
    container_name: booking_local_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data
        
        
  db_test:
    image: postgres:15-trixie
    container_name: booking_test_db
    environment:
      POSTGRES_DB: BookingTestDb
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5433:5432"
    volumes:
      - booking_test_db_data:/var/lib/postgresql/data

volumes:
  booking_db_data:
  booking_test_db_data: