apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: baggage
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: baggage_db
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: baggage
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: baggage
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=baggage_db;Username=postgres;Password=postgres"
  RabbitMQ__Username: guest
  RabbitMQ__Password: guest
