apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: airport
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: airport_system
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: airport
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: airport
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_DB_USERNAME: postgres
  KC_DB_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: airport
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=airport_system;Username=postgres;Password=postgres"
  Keycloak__ClientSecret: airport-api-secret
  RabbitMQ__Username: guest
  RabbitMQ__Password: guest
