apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 15692
          envFrom:
            - secretRef:
                name: rabbitmq-credentials
          volumeMounts:
            - name: plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 40
            periodSeconds: 30
      volumes:
        - name: plugins
          configMap:
            name: rabbitmq-plugins
